services:

  mariadb:
    image: mariadb:10.11
    container_name: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3310:3309"
    restart: always

volumes:
  mariadb_data:
    driver: local
  mysql_data:
    driver: local
